#!/usr/bin/env tsx
/**
 * acm-stub-build — write a deterministic ACM manifest + stub test files.
 *
 * Stub-mode tool. Used by phase-acm.yml when invocation_mode == 'stub' to
 * verify the state-machine wiring + branch creation + commit flow without
 * spending tokens on the live test-agent. Real test-agent generation
 * lands in step 6b.
 *
 * Each stub test deliberately FAILS so acm-verify --check-red reports
 * red on every criterion (which is what we want post-phase-acm — the test
 * stubs assert behavior the impl hasn't shipped yet). The simplest
 * always-fails test is `expect(false).toBe(true)`; we use that plus a
 * descriptive `it()` name so phase-implement's test runner output is
 * comprehensible to a human reviewing the run.
 *
 * Inputs (CLI args):
 *   --extract <path>       acm-extract.json output (criteria + spec_sha256)
 *   --issue <number>       issue number (used in test file names)
 *   --spec <path>          spec path (echoed into manifest)
 *   --manifest <path>      where to write .dev-agent/acm-manifest.json
 *   --tests-dir <path>     where to write tests/acm/*.test.ts
 *
 * Output: writes the manifest + tests to disk. Logs a summary.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  computeSha256,
  type ACMManifest,
  type CriterionBinding,
  type AcceptanceCriterion,
  type LintFinding,
} from '../acm';

interface Args {
  extract: string;
  issue: string;
  spec: string;
  manifest: string;
  testsDir: string;
}

export function parseArgs(argv: string[]): Args {
  const args: Partial<Args> = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--extract') args.extract = argv[++i];
    else if (a === '--issue') args.issue = argv[++i];
    else if (a === '--spec') args.spec = argv[++i];
    else if (a === '--manifest') args.manifest = argv[++i];
    else if (a === '--tests-dir') args.testsDir = argv[++i];
  }
  for (const k of ['extract', 'issue', 'spec', 'manifest', 'testsDir'] as const) {
    if (!args[k]) throw new Error(`missing required arg: --${k.replace(/([A-Z])/g, '-$1').toLowerCase()}`);
  }
  return args as Args;
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40)
    .replace(/-+$/g, '') || 'criterion';
}

function stubTestBody(criterion: AcceptanceCriterion, issue: string): string {
  // The stub test deliberately fails. The describe + it names carry the
  // criterion text so vitest output is human-readable. expect(false).toBe(true)
  // is the canonical "always-red" assertion.
  const safeText = criterion.text.replace(/`/g, "'");
  return `// Stub test generated by phase-acm (stub mode) for dev-agent issue #${issue}.
// This stub will be replaced by a real failing test in step 6b's live mode.
// The current behavior is intentional: every ACM stub fails so acm-verify
// --check-red reports red on entry to phase-implement.

import { describe, it, expect } from 'vitest';

describe('${criterion.id}', () => {
  it('${safeText}', () => {
    // Red on purpose — phase-implement must turn this green by shipping
    // the behavior described in the criterion above.
    expect(false).toBe(true);
  });
});
`;
}

export function buildStubArtifacts(
  extract: { criteria: AcceptanceCriterion[]; spec_sha256: string; lint?: LintFinding[] },
  args: Args,
): { manifest: ACMManifest; testFiles: Record<string, string> } {
  const testFiles: Record<string, string> = {};
  const bindings: CriterionBinding[] = [];

  for (const c of extract.criteria) {
    const slug = slugify(c.text);
    const idx = c.id.replace(/^AC-/, '');
    const testFile = `${args.testsDir.replace(/\/$/, '')}/${args.issue}-${idx}-${slug}.test.ts`;
    const body = stubTestBody(c, args.issue);
    testFiles[testFile] = body;
    bindings.push({
      ...c,
      test_file: testFile,
      test_name: `${c.id}: ${c.text}`,
      test_sha256: computeSha256(body),
    });
  }

  const manifest: ACMManifest = {
    spec_path: args.spec,
    spec_sha256: extract.spec_sha256,
    generated_at: new Date().toISOString(),
    criteria: bindings,
  };

  return { manifest, testFiles };
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  const extract = JSON.parse(readFileSync(args.extract, 'utf8')) as {
    criteria: AcceptanceCriterion[];
    spec_sha256: string;
  };
  const { manifest, testFiles } = buildStubArtifacts(extract, args);

  // Write tests first, then manifest. If any single write fails we fail
  // loudly so the workflow's salvage step can surface a clear error.
  for (const [path, body] of Object.entries(testFiles)) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, body, 'utf8');
  }

  // Atomic manifest write: tmp + rename so a crash mid-write doesn't leave
  // a half-formed JSON file that downstream readers would reject.
  mkdirSync(dirname(args.manifest), { recursive: true });
  const tmp = args.manifest + '.tmp';
  writeFileSync(tmp, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
  // Use renameSync for atomicity. Node's fs.renameSync wraps POSIX rename(2)
  // which is atomic on the same filesystem.
  const { renameSync } = await import('node:fs');
  renameSync(tmp, args.manifest);

  process.stdout.write(
    `acm-stub-build: wrote ${Object.keys(testFiles).length} stub tests + manifest to ${args.manifest}\n`,
  );
}

const invokedAsCli = process.argv[1] && process.argv[1] === fileURLToPath(import.meta.url);
if (invokedAsCli) {
  main().catch((err) => {
    process.stderr.write(`acm-stub-build failed: ${err instanceof Error ? err.message : String(err)}\n`);
    process.exit(2);
  });
}
